# Generated by Django 6.0.2 on 2026-03-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deceptive_security', '0001_initial'),
        ('users', '0003_tenant_isolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='canarytoken',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canary_tokens', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='honeypot',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honeypots', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='threathunt',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threat_hunts', to='users.tenant'),
        ),
    ]
