# Generated by Django 6.0.2 on 2026-03-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbom', '0001_initial'),
        ('users', '0003_tenant_isolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentvulnerability',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_vulnerabilities', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='sbomcomponent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sbom_components', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='sbomproject',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sbom_projects', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sbom_vulnerabilities', to='users.tenant'),
        ),
    ]
