# Generated by Django 6.0.2 on 2026-02-28 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enclave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enclave_type', models.CharField(choices=[('intel_sgx', 'Intel SGX'), ('amd_sev', 'AMD SEV'), ('arm_tee', 'ARM TEE'), ('custom', 'Custom')], default='intel_sgx', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initializing', 'Initializing'), ('active', 'Active'), ('paused', 'Paused'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('attestation_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('enclave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='confidential_computing.enclave')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
