# Generated by Django 6.0.2 on 2026-03-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidential_computing', '0001_initial'),
        ('users', '0003_tenant_isolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='enclave',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enclaves', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='securesession',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secure_sessions', to='users.tenant'),
        ),
    ]
