# Generated by Django 6.0.2 on 2026-03-06 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0002_tenant_isolation'),
        ('users', '0003_tenant_isolation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('file_access', 'File Access'), ('network_connection', 'Network Connection'), ('privilege_change', 'Privilege Change'), ('config_change', 'Configuration Change'), ('api_call', 'API Call'), ('data_export', 'Data Export'), ('failed_auth', 'Failed Authentication'), ('suspicious_activity', 'Suspicious Activity')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('resource', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('risk_score', models.FloatField(default=0.0)),
                ('is_anomaly', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='users.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RealTimeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('threat_detected', 'Threat Detected'), ('anomaly_detected', 'Anomaly Detected'), ('policy_violation', 'Policy Violation'), ('privilege_abuse', 'Privilege Abuse'), ('data_exfiltration', 'Data Exfiltration'), ('brute_force', 'Brute Force Attempt'), ('malware_detected', 'Malware Detected'), ('suspicious_login', 'Suspicious Login')], db_index=True, max_length=50)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('asset_affected', models.CharField(blank=True, max_length=255, null=True)),
                ('action_taken', models.JSONField(default=list)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.IntegerField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_time_alerts', to='users.tenant')),
                ('source_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='ml_model.securityevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('intrusion', 'Intrusion'), ('data_breach', 'Data Breach'), ('malware_detection', 'Malware Detection'), ('phishing', 'Phishing'), ('ddos', 'DDoS'), ('insider_threat', 'Insider Threat'), ('privilege_abuse', 'Privilege Abuse')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('contained', 'Contained'), ('remediated', 'Remediated'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('target_systems', models.JSONField(default=list)),
                ('affected_users', models.JSONField(default=list)),
                ('indicators', models.JSONField(default=list)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('automated_action', models.CharField(blank=True, max_length=100)),
                ('containment_status', models.CharField(blank=True, max_length=50)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_incidents', to='users.tenant')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('mttd', 'Mean Time To Detect'), ('mttr', 'Mean Time To Respond'), ('mttr_resolve', 'Mean Time To Resolve'), ('threat_count', 'Threat Count'), ('incident_rate', 'Incident Rate'), ('false_positive_rate', 'False Positive Rate'), ('coverage', 'Security Coverage'), ('compliance_score', 'Compliance Score'), ('risk_score', 'Overall Risk Score'), ('attack_surface', 'Attack Surface')], db_index=True, max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='count', max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('target', models.FloatField(blank=True, null=True)),
                ('trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_metrics', to='users.tenant')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_type', models.CharField(choices=[('malware', 'Malware'), ('phishing', 'Phishing'), ('ransomware', 'Ransomware'), ('apt', 'APT'), ('insider', 'Insider Threat'), ('botnet', 'Botnet'), ('cryptojacking', 'Cryptojacking')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=20)),
                ('indicator', models.CharField(db_index=True, max_length=500, unique=True)),
                ('indicator_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('confidence', models.FloatField(default=0.0)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('affected_assets', models.JSONField(default=list)),
                ('mitigations', models.JSONField(default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threat_intelligence', to='users.tenant')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='ThreatPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('breach_likelihood', 'Breach Likelihood'), ('attack_vector', 'Attack Vector Prediction'), ('risk_score', 'Risk Score'), ('anomaly_score', 'Anomaly Score'), ('exploit_probability', 'Exploit Probability')], db_index=True, max_length=50)),
                ('target', models.CharField(max_length=255)),
                ('prediction', models.JSONField()),
                ('confidence', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(max_length=20)),
                ('factors', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('model_version', models.CharField(max_length=50)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threat_predictions', to='users.tenant')),
            ],
            options={
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['tenant', '-timestamp'], name='ml_model_se_tenant__e58088_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['tenant', 'event_type', '-timestamp'], name='ml_model_se_tenant__aa3578_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimealert',
            index=models.Index(fields=['tenant', '-created_at'], name='ml_model_re_tenant__892c61_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimealert',
            index=models.Index(fields=['tenant', 'priority', '-created_at'], name='ml_model_re_tenant__4469b0_idx'),
        ),
        migrations.AddIndex(
            model_name='securitymetric',
            index=models.Index(fields=['tenant', 'metric_type', '-recorded_at'], name='ml_model_se_tenant__bd6906_idx'),
        ),
    ]
