# Generated by Django 6.0.2 on 2026-03-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_trail', '0001_initial'),
        ('users', '0003_tenant_isolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='users.tenant'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('access', 'Access'), ('export', 'Export'), ('import', 'Import'), ('custom', 'Custom')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
