# Generated by Django 6.0.2 on 2026-03-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaches', '0001_initial'),
        ('users', '0003_tenant_isolation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breach',
            options={'ordering': ['-date_detected']},
        ),
        migrations.AddField(
            model_name='breach',
            name='affected_systems',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='breach',
            name='remediation_steps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='breach',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='breach',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breaches', to='users.tenant'),
        ),
        migrations.AlterField(
            model_name='breach',
            name='date_detected',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='breach',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='breach',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, max_length=20),
        ),
    ]
