# Generated by Django 6.0.2 on 2026-03-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soar', '0001_initial'),
        ('users', '0003_tenant_isolation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playbook',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='playbookrun',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='playbook',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='playbookrun',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playbook_runs', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='securityagent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_agents', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='users.tenant'),
        ),
    ]
