# Generated by Django 6.0.2 on 2026-02-28 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=255)),
                ('access_level', models.CharField(max_length=50)),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('laptop', 'Laptop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], max_length=50)),
                ('keystroke_pattern', models.JSONField(default=dict)),
                ('mouse_movement_pattern', models.JSONField(default=dict)),
                ('touch_pattern', models.JSONField(default=dict)),
                ('voice_pattern', models.JSONField(blank=True, default=dict)),
                ('behavioral_score', models.FloatField(default=100.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Web3Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=100, unique=True)),
                ('did', models.CharField(max_length=255, unique=True)),
                ('nonce', models.CharField(max_length=100)),
                ('signature', models.TextField(blank=True)),
                ('chain_id', models.IntegerField(default=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web3_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZTNAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.JSONField(default=dict)),
                ('device_fingerprint', models.CharField(max_length=500)),
                ('trust_score', models.FloatField(default=50.0)),
                ('access_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('is_trusted', models.BooleanField(default=False)),
                ('risk_level', models.CharField(default='unknown', max_length=50)),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('session_active', models.BooleanField(default=False)),
                ('session_expires_at', models.DateTimeField(blank=True, null=True)),
                ('jit_access', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ztna_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
