# Generated by Django 6.0.2 on 2026-03-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tenant_isolation'),
        ('ztna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='biometricprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_profiles', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='web3identity',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web3_identities', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='ztnaprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ztna_profiles', to='users.tenant'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='resource',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='biometricprofile',
            name='device_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='biometricprofile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='web3identity',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='web3identity',
            name='wallet_address',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ztnaprofile',
            name='access_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='ztnaprofile',
            name='device_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ztnaprofile',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ztnaprofile',
            name='is_trusted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='ztnaprofile',
            name='risk_level',
            field=models.CharField(db_index=True, default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='ztnaprofile',
            name='session_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
