# Generated by Django 6.0.2 on 2026-02-28 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('algorithm', models.CharField(choices=[('aes256', 'AES-256'), ('aes512', 'AES-512'), ('rsa4096', 'RSA-4096'), ('rsa8192', 'RSA-8192'), ('kyber512', 'Kyber-512'), ('kyber1024', 'Kyber-1024'), ('dilithium2', 'Dilithium-2'), ('dilithium3', 'Dilithium-3')], max_length=50)),
                ('key_data', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotated_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='quantum_crypto.encryptionkey')),
                ('old_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='quantum_crypto.encryptionkey')),
                ('rotated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rotated_at'],
            },
        ),
    ]
