# Generated by Django 6.0.2 on 2026-03-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_audits', '0001_initial'),
        ('users', '0003_tenant_isolation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudauditresult',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='cloudauditresult',
            name='cloud_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cloudauditresult',
            name='remediation_steps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cloudauditresult',
            name='resource_arn',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cloudauditresult',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='cloudauditresult',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloud_audits', to='users.tenant'),
        ),
    ]
